# syntax=docker/dockerfile:1.4
# =============================================================================
# Multi-stage Dockerfile for FastAPI Applications
# Uses: uv (fast Python package manager), GAR for private packages
# Supports: Alpine Linux AND Debian-based images (slim, bookworm)
# Compatible with: GCP Cloud Run, AWS ECS, Azure Container Apps, DigitalOcean
# Generated by Lighthouse CLI
#
# Optimizations applied:
# - Minimal build dependencies (no rust/cargo - cryptography ships wheels)
# - Selective COPY to avoid invalidating layer cache
# - Copy with --chown to avoid slow chown -R operations
# - Minimal runtime dependencies
# - Auto-detection of Alpine vs Debian for package manager commands
# =============================================================================

ARG BASE_IMAGE=python:3.12-alpine

# =============================================================================
# Stage 1: Builder - Install dependencies with uv
# =============================================================================
FROM ${BASE_IMAGE} AS builder

# Install build dependencies - auto-detect Alpine vs Debian
# Note: rust/cargo removed - cryptography now ships manylinux wheels
# Includes GDAL/PROJ/GEOS for geospatial packages (geopandas, pyogrio, cartopy)
RUN if command -v apk > /dev/null 2>&1; then \
        # Alpine Linux
        apk add --no-cache gcc g++ musl-dev postgresql-dev libffi-dev git curl \
            gdal-dev proj-dev geos-dev; \
    else \
        # Debian/Ubuntu
        apt-get update && apt-get install -y --no-install-recommends \
            gcc g++ libpq-dev libffi-dev git curl ca-certificates \
            libgdal-dev libproj-dev libgeos-dev \
        && rm -rf /var/lib/apt/lists/*; \
    fi

# Install uv for fast Python package management
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_PREFERENCE=only-system \
    UV_PYTHON=/usr/local/bin/python3

WORKDIR /app

# Build arguments for Google Artifact Registry (GAR) authentication
ARG GAR_TOKEN=""
ARG GAR_REGION=europe-west1
ARG GAR_PROJECT=apps-aecs4u
ARG GAR_REPOSITORY=python-packages

# Configure GAR as extra index URL if token provided
ENV UV_EXTRA_INDEX_URL=${GAR_TOKEN:+"https://oauth2accesstoken:${GAR_TOKEN}@${GAR_REGION}-python.pkg.dev/${GAR_PROJECT}/${GAR_REPOSITORY}/simple/"}

# Copy dependency files first (for layer caching)
COPY pyproject.toml uv.lock ./

# Install dependencies with uv into a virtual environment
# --frozen ensures lockfile is used exactly
# --no-dev excludes development dependencies
RUN uv venv /app/.venv && \
    . /app/.venv/bin/activate && \
    uv sync --frozen --no-dev --no-install-project

# Copy only necessary application code (not tests, docs, scripts)
COPY codice_fiscale/ ./codice_fiscale/

# Install the project itself
RUN . /app/.venv/bin/activate && uv sync --frozen --no-dev

# =============================================================================
# Stage 2: Runtime - Minimal production image
# =============================================================================
FROM ${BASE_IMAGE} AS runtime

# Install runtime dependencies - auto-detect Alpine vs Debian
# Includes GDAL/PROJ/GEOS runtime libs for geospatial packages
RUN if command -v apk > /dev/null 2>&1; then \
        # Alpine Linux
        apk add --no-cache libpq libffi tini curl gdal proj geos; \
    else \
        # Debian/Ubuntu
        apt-get update && apt-get install -y --no-install-recommends \
            libpq5 libffi8 tini curl ca-certificates \
            libgdal34 libproj25 libgeos3.12.1 \
        && rm -rf /var/lib/apt/lists/*; \
    fi

# Create non-root user for security - auto-detect Alpine vs Debian
RUN if command -v apk > /dev/null 2>&1; then \
        # Alpine Linux uses adduser with different flags
        adduser -D -u 1000 -g 1000 appuser; \
    else \
        # Debian/Ubuntu uses adduser or useradd
        useradd -m -u 1000 -U appuser; \
    fi

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app \
    PATH="/app/.venv/bin:${PATH}" \
    VIRTUAL_ENV=/app/.venv \
    PORT=8080

WORKDIR /app

# Copy virtual environment from builder (already has correct permissions)
COPY --from=builder --chown=appuser:appuser /app/.venv /app/.venv

# Copy application code from builder
COPY --from=builder --chown=appuser:appuser /app/codice_fiscale /app/codice_fiscale
COPY --from=builder --chown=appuser:appuser /app/pyproject.toml /app/

# Create directories and entrypoint in one layer
RUN mkdir -p /app/static /app/templates /app/data && \
    chown -R appuser:appuser /app/static /app/templates /app/data && \
    SITE_PACKAGES=$(ls -d /app/.venv/lib/python*/site-packages | head -1) && \
    printf "#!/bin/sh\nexport PYTHONPATH=%s:/app\nexec python -m uvicorn codice_fiscale.main:app --host 0.0.0.0 --port 8080\n" "$SITE_PACKAGES" > /app/entrypoint.sh && \
    chmod +x /app/entrypoint.sh

USER appuser

EXPOSE 8080

# Health check for container orchestrators
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:8080/health || exit 1

# Use tini as init system for proper signal handling
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/app/entrypoint.sh"]

# =============================================================================
# Stage 3: Development - Includes dev tools and hot reload
# =============================================================================
FROM runtime AS development

# Switch to root for installing dev tools
USER root

# Install uv in development image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Install development dependencies
RUN uv pip install --system \
    pytest \
    pytest-cov \
    pytest-asyncio \
    ruff \
    mypy \
    ipython

# Switch back to appuser
USER appuser

# Override CMD for development (with reload)
CMD ["uvicorn", "codice_fiscale.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
